# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Gazettes Kenya
email: gazettes@codeforafrica.org
url: http://opengazettes.or.ke
baseurl:
description: Making Kenyan Government Gazettes freely available.
twitter:
  username: code4sa
logo: /img/logo.png

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  gazettes:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
    values:
      image: /img/banner_5.png

# Build settings
markdown: kramdown
exclude: [vendor]
